sudo: required

services:
  - docker

git:
  depth: 1

install:
  - docker pull simexp/niak_dependency:1.1

script:
  - docker run -it --privileged -v $PWD:$PWD simexp/niak_dependency:1.1 /bin/bash -lic "cd $PWD; octave --eval \"addpath(genpath(pwd));[pipe,opt,status] = niak_test_all(struct(),struct('psom',struct('mode_pipeline_manager','session','mode','background','max_queued',2,'flag_pause',false),'partial','stability_rest')) ;system('cat result/report_test_regression_stability_rest_demoniak.csv');psom_pipeline_visu('/home/travis/build/SIMEXP/niak/result/logs/','log','basc_test_stability_rest_demoniak') , exit(status)\""

notifications:
  email: false
  slack: simexp:eFh4jwo2RWWvSoafeVx9xzoU
